# Generated by Django 3.2.3 on 2021-06-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
