# Generated by Django 3.2.3 on 2021-06-05 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(choices=[('Ağdam', 'Ağdam'), ('Ağdaş', 'Ağdaş'), ('Agcabedi', 'Agcabedi'), ('Ağstafa', 'Ağstafa'), ('Astara', 'Astara'), ('Ağsu', 'Ağsu'), ('Bakı', 'Bakı'), ('Balakən', 'Balakən'), ('Beyləqan', 'Beyləqan'), ('Bərdə', 'Bərdə'), ('Biləsuvar', 'Biləsuvar'), ('Cəbrayıl', 'Cəbrayıl'), ('Cəliləbad', 'Cəliləbad'), ('Culfa', 'Culfa'), ('Daşkəsən', 'Daşkəsən'), ('Dəliməmmədli', 'Dəliməmmədli'), ('Füzuli', 'Füzuli'), ('Gədəbəy', 'Gədəbəy'), ('Gəncə', 'Gəncə'), ('Goranboy', 'Goranboy'), ('Göyçay', 'Göyçay'), ('Hacıqabul', 'Hacıqabul'), ('İmişli', 'İmişli'), ('İsmayıllı', 'İsmayıllı'), ('Kürdəmir', 'Kürdəmir'), ('Lerik', 'Lerik'), ('Lənkəran', 'Lənkəran'), ('Masallı', 'Masallı'), ('Mingəçəvir', 'Mingəçəvir'), ('Naftalan', 'Naftalan'), ('Naxçıvan', 'Naxçıvan'), ('Nefçala', 'Nefçala'), ('Oğuz', 'Oğuz'), ('Qax', 'Qax'), ('Qazax', 'Qazax'), ('Qəbələ', 'Qəbələ'), ('Qobustan', 'Qobustan'), ('Quba', 'Quba'), ('Qusar', 'Qusar'), ('Saatlı', 'Saatlı'), ('Sabirabad', 'Sabirabad'), ('Şabran', 'Şabran'), ('Şahbuz', 'Şahbuz'), ('Salyan', 'Salyan'), ('Şamaxı', 'Şamaxı'), ('Şamux', 'Şamux'), ('Şəki', 'Şəki'), ('Şəmkir', 'Şəmkir'), ('Şərur', 'Şərur'), ('Şirvan', 'Şirvan'), ('Siyəzən', 'Siyəzən'), ('Sumqayıt', 'Sumqayıt'), ('Tərtər', 'Tərtər'), ('Tovuz', 'Tovuz'), ('Ucar', 'Ucar'), ('Xaçmaz', 'Xaçmaz'), ('Xırdalan', 'Xırdalan'), ('Xızı', 'Xızı'), ('Xudat', 'Xudat'), ('Yardımlı', 'Yardımlı'), ('Yevlax', 'Yevlax'), ('Zaqatala', 'Zaqatala'), ('Zərdab', 'Zərdab')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.CharField(choices=[('Elektronika', 'Elektronika'), ('Avtomobil', 'Avtomobil'), ('Daşınmaz əmlak', 'Daşınmaz əmlak')], max_length=100),
        ),
    ]
