# Generated by Django 3.2.3 on 2021-06-05 21:12

from django.db import migrations
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20210606_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=post.models.IntegerRangeField(verbose_name='Qiymət (AZN)'),
        ),
    ]
